upgrade install script

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,17 +1,36 @@
 #!/bin/bash
 
+#=================================================
+# GENERIC START
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+source /usr/share/yunohost/helpers
+
+#=================================================
+# MANAGE SCRIPT FAILURE
+#=================================================
+
 # Exit on command errors and treat unset variables as an error
 set -eu
 
-source _common	# Loads the generic functions usually used in the script
-source /usr/share/yunohost/helpers # Source app helpers
+ynh_abort_if_errors	# Active trap to stop the script if an error is detected.
 
 ynh_clean_setup () {
 	# Clean installation residues that are not supported by the remove script.
 	# Clean hosts
 	echo ""
 }
-ynh_abort_if_errors	# Active trap to stop the script if an error is detected.
+
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+domain=$YNH_APP_ARG_DOMAIN
+path_url=$YNH_APP_ARG_PATH
+is_public=$YNH_APP_ARG_IS_PUBLIC
 
 domain=$YNH_APP_ARG_DOMAIN
 path=$YNH_APP_ARG_PATH
@@ -19,14 +38,31 @@ token_telegram=$YNH_APP_ARG_TOKEN_TELEGRAM
 user_github=$YNH_APP_ARG_USER_GITHUB
 token_github=$YNH_APP_ARG_TOKEN_GITHUB
 
-app=$YNH_APP_INSTANCE_NAME
+# Final path is the classic name for "where we will put the source of the app"
+final_path=/var/www/$app
+
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
+#=================================================
+ynh_script_progression --message="Validating installation parameters..." --weight=1
 
 CHECK_VAR "$app" "app name not set"
-
-# Check and fix path syntax.
-path=$(ynh_normalize_url_path $path)
 CHECK_DOMAINPATH
 CHECK_FINALPATH
+
+# Check final_path availability
+test ! -e "$final_path" || ynh_die "$final_path already exists, aborting"
+
+# Register (book) the web path
+# not needed ynh_webpath_register $app $domain $path_url
+
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
+
+ynh_script_progression --message="Storing installation settings..." --weight=1
+
+source _common	# Loads the generic functions usually used in the script
 
 ynh_app_setting_set $app domain $domain
 ynh_app_setting_set $app path $path
@@ -36,6 +72,11 @@ ynh_app_setting_set $app token_github $token_github
 
 # Create system user dedicace for this app
 ynh_system_user_create $app
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+ynh_script_progression --message="Setting up source files..." --weight=1
 
 # Creates the destination directory and stores its location.
 sudo mkdir "$final_path"
@@ -79,11 +120,22 @@ sudo cp -a ../conf/dist $final_path
 
 sudo chown $app: /var/log/$app/
 
-# Modify Nginx configuration file and copy it to Nginx conf directory
-ynh_nginx_config
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
+ynh_script_progression --message="Configuring nginx web server..." --weight=1
+
+# Create a dedicated nginx config
+ynh_add_nginx_config
 
 # Add logrotate
 ynh_use_logrotate
 
-# Reload Nginx
-sudo service nginx reload
+#=================================================
+# RELOAD NGINX
+#=================================================
+ynh_script_progression --message="Reloading nginx web server..." --weight=1
+
+ynh_systemd_action --action=reload --service_name=nginx
+
+ynh_script_progression --message="Installation of $app completed" --last
